In [63]:
%pylab
%matplotlib inline

Using matplotlib backend: Qt4Agg
Populating the interactive namespace from numpy and matplotlib


In [64]:
data = array([36, 37.5, 38, 44.5, 43])
toeval = randn(5) * 100

In [65]:
data * 6

array([ 216.,  225.,  228.,  267.,  258.])

In [66]:
data * toeval

array([-5533.58295045,   137.70869494,  -674.72811807,  5996.02241794,
        2859.98123481])

In [67]:
dot(data, toeval)

2785.4012791777423

In [68]:
sqrt(data)

array([ 6.        ,  6.12372436,  6.164414  ,  6.67083203,  6.55743852])

In [69]:
mean(data)

39.799999999999997

In [70]:
std(data, ddof=1)

3.7181984885156414

In [71]:
data.mean()

39.799999999999997

In [72]:
data.std(ddof=1)

3.7181984885156414

In [73]:
ones((3, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [74]:
data = array([
        [1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
    ])

In [75]:
data

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [76]:
data.shape

(3, 3)

In [77]:
data.reshape((1, 9))

array([[1, 0, 0, 0, 1, 0, 0, 0, 1]])

In [78]:
array([1, 0, 0, 0, 1, 0, 0, 0, 1]).reshape((3, 3))

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [79]:
array([i for i in range(81)]).reshape((9, 9))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80]])